version: "3.9"

services:
  web:
    image: pasakalam/nginx-php:alpine
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 135vM8dt7Z7JYlT
      POSTGRES_DB: sre
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
